name: Publish docs
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
     
      - name: Doxygen
        uses: mattnotmitt/doxygen-action@v1.1.0
        with:
          working-directory: docs
      
      - name: Sphinx
        uses: ammaraskar/sphinx-action@0.4
        with:
          docs-folder: docs
          build-command: sphinx-build source build

      - name: Upload
        uses: actions/upload-pages-artifact@v1.0.4
        with:
          path: docs/build

  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1.1.0
